User.create(first_name: "Josh", last_name: "Ullman", email: "boredoranges@yahoo.com", username: "CaptainPlanet", password: "password")
User.create(first_name: "Alex", last_name: "Cusack", email: "boredoranges@yahoo.com", username: "Kuzy", password: "password")
User.create(first_name: "David", last_name: "Grotting", email: "boredoranges@yahoo.com", username: "BuffaloKing", password: "password")
User.create(first_name: "Vivek", last_name: "Poola", email: "boredoranges@yahoo.com", username: "TheWizard", password: "password")
User.create(first_name: "Arielle", last_name: "Chen", email: "boredoranges@yahoo.com", username: "Banana", password: "password")
User.create(first_name: "Le", last_name: "Tran", email: "boredoranges@yahoo.com", username: "BlackWidow", password: "password")
User.create(first_name: "Eric", last_name: "Saxman", email: "boredoranges@yahoo.com", username: "TheSaxMan", password: "password")
User.create(first_name: "Carissa", last_name: "Blossom", email: "boredoranges@yahoo.com", username: "Carissi", password: "password")
User.create(first_name: "Ellis", last_name: "Marte", email: "boredoranges@yahoo.com", username: "Chompy", password: "password")
User.create(first_name: "James", last_name: "Newman", email: "boredoranges@yahoo.com", username: "WolfMan", password: "password")
User.create(first_name: "Mike", last_name: "Farr", email: "boredoranges@yahoo.com", username: "MasterMike", password: "password")
User.create(first_name: "Travis", last_name: "S", email: "boredoranges@yahoo.com", username: "WhitePearl", password: "password")
User.create(first_name: "Alex", last_name: "Kass", email: "boredoranges@yahoo.com", username: "Kassanova", password: "password")
User.create(first_name: "Patrick", last_name: "Betti", email: "boredoranges@yahoo.com", username: "Scoobs", password: "password")
User.create(first_name: "Jeff", last_name: "Chang", email: "boredoranges@yahoo.com", username: "Chefe", password: "password")
User.create(first_name: "Andrew", last_name: "Donato", email: "boredoranges@yahoo.com", username: "TheAdmiral", password: "password")
User.create(first_name: "Jennifer", last_name: "Jaochico", email: "boredoranges@yahoo.com", username: "Jenga", password: "password")
User.create(first_name: "Ian", last_name: "Harris", email: "boredoranges@yahoo.com", username: "Banner", password: "password")
User.create(first_name: "Brian", last_name: "Kennedy", email: "boredoranges@yahoo.com", username: "BigKahuna", password: "password")
User.create(first_name: "Benoit", last_name: "Demonsant", email: "boredoranges@yahoo.com", username: "BennyAndTheJets", password: "password")
User.create(first_name: "Diana", last_name: "Lozano", email: "boredoranges@yahoo.com", username: "TheDragon", password: "password")
User.create(first_name: "Eric", last_name: "Flores", email: "boredoranges@yahoo.com", username: "EZE", password: "password")
User.create(first_name: "Henry", last_name: "Vega", email: "boredoranges@yahoo.com", username: "ActionHank", password: "password")
User.create(first_name: "Karan", last_name: "Aditya", email: "boredoranges@yahoo.com", username: "TheMatador", password: "password")
User.create(first_name: "Kelvin", last_name: "Gann", email: "boredoranges@yahoo.com", username: "SubZero", password: "password")
User.create(first_name: "Nicholas", last_name: "Toulouse", email: "boredoranges@yahoo.com", username: "WildCard", password: "password")
User.create(first_name: "Staunton", last_name: "Sample", email: "boredoranges@yahoo.com", username: "KarateKid", password: "password")

Tag.create(name: "hiking")
Tag.create(name: "surfing")
Tag.create(name: "assassination")
Tag.create(name: "sexy")
UserTag.create(user_id: 15, tag_id: 1)
UserTag.create(user_id: 18, tag_id: 1)
UserTag.create(user_id: 20, tag_id: 1)
UserTag.create(user_id: 5, tag_id: 1)
UserTag.create(user_id: 9, tag_id: 1)
UserTag.create(user_id: 7, tag_id: 1)
UserTag.create(user_id: 13, tag_id: 1)
UserTag.create(user_id: 3, tag_id: 2)
UserTag.create(user_id: 7, tag_id: 4)
UserTag.create(user_id: 6, tag_id: 3)
